import {createConstant} from './../../utils';

export default createConstant(
	'ADD_GENERATED_WORLD', 'REMOVE_GENERATED_WORLD', 'RECEIVE_GENERATED_WORLDS', 'ADD_PENDING_GENERATED_WORLD',
	'REMOVE_PENDING_GENERATED_WORLD', 'ADD_ERRORED_GENERATED_WORLD', 'REMOVE_ERRORED_GENERATED_WORLD',
	'RECEIVE_WORLD_SITES_AND_POPS', 'ADD_WORLD_SITES_AND_POPS'
);
